# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Mon May  5 14:44:04 2014

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class PeakFitDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PeakFitDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.lbName = wx.StaticText(self, -1, "Peak name")
        self.tcPeakName = wx.TextCtrl(self, -1, "")
        self.lbPosition = wx.StaticText(self, -1, "Position")
        self.tcPositionX = wx.TextCtrl(self, -1, "")
        self.tcPositionY = wx.TextCtrl(self, -1, "")
        self.lbWidth = wx.StaticText(self, -1, "Widths")
        self.tcSigmaX = wx.TextCtrl(self, -1, "")
        self.tcSigmaY = wx.TextCtrl(self, -1, "")
        self.lbAngle = wx.StaticText(self, -1, "Angle")
        self.tcAngle = wx.TextCtrl(self, -1, "")
        self.lbScale = wx.StaticText(self, -1, "Scale")
        self.tcScale = wx.TextCtrl(self, -1, "")
        self.lbBackground = wx.StaticText(self, -1, "Background")
        self.tcBackground = wx.TextCtrl(self, -1, "")
        self.bCancel = wx.Button(self, wx.ID_CANCEL, "Cancel")
        self.bApply = wx.Button(self, wx.ID_APPLY, "Apply")
        self.bOK = wx.Button(self, wx.ID_OK, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PeakFitDialog.__set_properties
        self.SetTitle("Fit peak")
        self.tcPeakName.SetMinSize((150, 29))
        self.lbPosition.SetMinSize((70, 19))
        self.lbWidth.SetMinSize((70, 19))
        self.lbAngle.SetMinSize((70, 19))
        self.lbScale.SetMinSize((100, 19))
        self.lbBackground.SetMinSize((100, 19))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PeakFitDialog.__do_layout
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_30 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_29 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_27 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_24 = wx.BoxSizer(wx.VERTICAL)
        sizer_26 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_25 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_28 = wx.BoxSizer(wx.VERTICAL)
        sizer_28.Add(self.lbName, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_28.Add(self.tcPeakName, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_13.Add(sizer_28, 0, wx.ALL | wx.EXPAND, 10)
        sizer_25.Add(self.lbPosition, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_25.Add(self.tcPositionX, 0, 0, 0)
        sizer_25.Add(self.tcPositionY, 0, 0, 0)
        sizer_24.Add(sizer_25, 1, wx.EXPAND, 0)
        sizer_26.Add(self.lbWidth, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_26.Add(self.tcSigmaX, 0, 0, 0)
        sizer_26.Add(self.tcSigmaY, 0, 0, 0)
        sizer_24.Add(sizer_26, 1, wx.EXPAND, 0)
        sizer_22.Add(sizer_24, 1, wx.ALL | wx.EXPAND, 10)
        sizer_27.Add(self.lbAngle, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_27.Add(self.tcAngle, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_22.Add(sizer_27, 1, wx.ALL | wx.EXPAND, 10)
        sizer_13.Add(sizer_22, 1, wx.EXPAND, 0)
        sizer_29.Add(self.lbScale, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_29.Add(self.tcScale, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_23.Add(sizer_29, 1, wx.ALL | wx.EXPAND, 10)
        sizer_30.Add(self.lbBackground, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_30.Add(self.tcBackground, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_23.Add(sizer_30, 1, wx.ALL | wx.EXPAND, 10)
        sizer_13.Add(sizer_23, 1, wx.EXPAND, 0)
        sizer_11.Add(sizer_13, 1, wx.EXPAND, 0)
        sizer_12.Add((150, 30), 0, 0, 0)
        sizer_12.Add(self.bCancel, 0, 0, 0)
        sizer_12.Add(self.bApply, 0, 0, 0)
        sizer_12.Add(self.bOK, 0, 0, 0)
        sizer_11.Add(sizer_12, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_11)
        sizer_11.Fit(self)
        self.Layout()
        # end wxGlade

# end of class PeakFitDialog
